version: '3.2'

services:
  transactions-api:
    image: transactions-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
  transactions-api-test:
    image: transactions-api-test
    build:
      context: .
      dockerfile: Dockerfile
    links:
     - transactions-api