version: '3.2'

services:
  base-api:
    image: base-api
    build:
      context: base-api/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - UH_URL=my-local-db-connection-string;
#TODO: Add a development database

  base-api-test:
    image: base-api-test
    build:
      context: .
      dockerfile: base-api.Tests/Dockerfile
    links:
      - stub-test-db
  stub-test-db:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432


